/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package randomapp;

/**
 *
 * @author gabriele.urban
 */
public class Estrazione extends javax.swing.JPanel {

    /**
     * Creates new form Pannello
     */
    public Estrazione() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        t5 = new javax.swing.JLabel();
        t6 = new javax.swing.JLabel();
        t7 = new javax.swing.JLabel();
        t8 = new javax.swing.JLabel();
        t9 = new javax.swing.JLabel();
        t10 = new javax.swing.JLabel();
        t11 = new javax.swing.JLabel();
        t12 = new javax.swing.JLabel();
        t13 = new javax.swing.JLabel();
        t14 = new javax.swing.JLabel();
        t15 = new javax.swing.JLabel();
        t16 = new javax.swing.JLabel();
        t17 = new javax.swing.JLabel();
        t18 = new javax.swing.JLabel();
        t19 = new javax.swing.JLabel();
        t20 = new javax.swing.JLabel();
        t21 = new javax.swing.JLabel();
        t22 = new javax.swing.JLabel();
        t23 = new javax.swing.JLabel();
        t24 = new javax.swing.JLabel();
        t25 = new javax.swing.JLabel();
        t26 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.setText("Nome1");
        add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        t2.setText("Nome2");
        add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 45, -1, -1));

        t3.setText("Nome3");
        add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 78, 34, -1));

        t4.setText("Nome4");
        add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 111, -1, -1));

        t5.setText("Nome5");
        add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 144, -1, -1));

        t6.setText("Nome6");
        add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 177, -1, -1));

        t7.setText("Nome7");
        add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 210, -1, -1));

        t8.setText("Nome8");
        add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 243, 34, -1));

        t9.setText("Nome9");
        add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 276, -1, -1));

        t10.setText("Nome10");
        add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 12, -1, -1));

        t11.setText("Nome11");
        add(t11, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 45, -1, -1));

        t12.setText("Nome12");
        add(t12, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 78, -1, -1));

        t13.setText("Nome13");
        add(t13, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 111, 40, -1));

        t14.setText("Nome14");
        add(t14, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 144, -1, -1));

        t15.setText("Nome15");
        add(t15, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 177, -1, -1));

        t16.setText("Nome16");
        add(t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 210, -1, -1));

        t17.setText("Nome17");
        add(t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 243, 40, -1));

        t18.setText("Nome18");
        add(t18, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 276, -1, -1));

        t19.setText("Nome19");
        add(t19, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 12, -1, -1));

        t20.setText("Nome20");
        add(t20, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 45, -1, -1));

        t21.setText("Nome21");
        add(t21, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 78, 44, -1));

        t22.setText("Nome22");
        add(t22, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 111, -1, -1));

        t23.setText("Nome23");
        add(t23, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 144, -1, -1));

        t24.setText("Nome24");
        add(t24, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 177, -1, -1));

        t25.setText("Nome25");
        add(t25, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 210, -1, -1));

        t26.setText("Nome26");
        add(t26, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 243, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t10;
    private javax.swing.JLabel t11;
    private javax.swing.JLabel t12;
    private javax.swing.JLabel t13;
    private javax.swing.JLabel t14;
    private javax.swing.JLabel t15;
    private javax.swing.JLabel t16;
    private javax.swing.JLabel t17;
    private javax.swing.JLabel t18;
    private javax.swing.JLabel t19;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t20;
    private javax.swing.JLabel t21;
    private javax.swing.JLabel t22;
    private javax.swing.JLabel t23;
    private javax.swing.JLabel t24;
    private javax.swing.JLabel t25;
    private javax.swing.JLabel t26;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel t6;
    private javax.swing.JLabel t7;
    private javax.swing.JLabel t8;
    private javax.swing.JLabel t9;
    // End of variables declaration//GEN-END:variables
}
