/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanel;

/**
 *
 * @author gabriele.urban
 */
public class MainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainJPanel
     */
    public MainJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelcateto1 = new javax.swing.JLabel();
        labelcateto2 = new javax.swing.JLabel();
        testocateto1 = new javax.swing.JTextField();
        testocateto2 = new javax.swing.JTextField();
        pulsanteCalcola = new javax.swing.JButton();
        risultato = new javax.swing.JLabel();
        Titolo = new javax.swing.JLabel();
        ipotenusa = new javax.swing.JLabel();
        testoipotenusa = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelcateto1.setText("cateto 1");
        add(labelcateto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        labelcateto2.setText("cateto 2");
        add(labelcateto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        testocateto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testocateto1ActionPerformed(evt);
            }
        });
        add(testocateto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 98, -1));

        testocateto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testocateto2ActionPerformed(evt);
            }
        });
        add(testocateto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 98, -1));

        pulsanteCalcola.setText("calcola");
        pulsanteCalcola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteCalcolaActionPerformed(evt);
            }
        });
        add(pulsanteCalcola, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        risultato.setBackground(new java.awt.Color(0, 0, 0));
        risultato.setForeground(new java.awt.Color(0, 146, 0));
        risultato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        risultato.setText("dato calcolato");
        risultato.setToolTipText("");
        risultato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 0, 15), 1, true));
        add(risultato, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 120, 30));

        Titolo.setText("Calcolatore area triangolo");
        add(Titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        ipotenusa.setText("ipotenusa");
        add(ipotenusa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        testoipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testoipotenusaActionPerformed(evt);
            }
        });
        add(testoipotenusa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 98, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void testocateto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testocateto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testocateto1ActionPerformed

    private void pulsanteCalcolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteCalcolaActionPerformed
        try{
            float a = Float.parseFloat(testocateto1.getText());
            float b = Float.parseFloat(testocateto2.getText());
            float c = Float.parseFloat(testoipotenusa.getText());
            float s = (a + b + c)/2;
            float area = (float) Math.sqrt(s*(s-a)*(s-b)*(s-c));
            risultato.setText("area: " + area);
        }catch(NumberFormatException e){
            risultato.setText("Valori non validi");
        }
    }//GEN-LAST:event_pulsanteCalcolaActionPerformed

    private void testocateto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testocateto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testocateto2ActionPerformed

    private void testoipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testoipotenusaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testoipotenusaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titolo;
    private javax.swing.JLabel ipotenusa;
    private javax.swing.JLabel labelcateto1;
    private javax.swing.JLabel labelcateto2;
    private javax.swing.JButton pulsanteCalcola;
    private javax.swing.JLabel risultato;
    private javax.swing.JTextField testocateto1;
    private javax.swing.JTextField testocateto2;
    private javax.swing.JTextField testoipotenusa;
    // End of variables declaration//GEN-END:variables
}
