/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanel;

/**
 *
 * @author gabriele.urban
 */
public class MainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainJPanel
     */
    public MainJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBase = new javax.swing.JLabel();
        labelAltezza = new javax.swing.JLabel();
        testoBase = new javax.swing.JTextField();
        testoAltezza = new javax.swing.JTextField();
        pulsanteCalcola = new javax.swing.JButton();
        risultato = new javax.swing.JLabel();

        labelBase.setText("base");

        labelAltezza.setText("altezza");

        testoBase.setText("inserisci base");
        testoBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testoBaseActionPerformed(evt);
            }
        });

        testoAltezza.setText("inserisci altezza");
        testoAltezza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testoAltezzaActionPerformed(evt);
            }
        });

        pulsanteCalcola.setText("calcola");
        pulsanteCalcola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteCalcolaActionPerformed(evt);
            }
        });

        risultato.setText("dato calcolato");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(risultato)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelBase)
                                .addComponent(labelAltezza))
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(testoAltezza)
                                .addComponent(testoBase)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(153, 153, 153)
                            .addComponent(pulsanteCalcola))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBase)
                    .addComponent(testoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAltezza)
                    .addComponent(testoAltezza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(pulsanteCalcola)
                .addGap(33, 33, 33)
                .addComponent(risultato)
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void testoBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testoBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testoBaseActionPerformed

    private void pulsanteCalcolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteCalcolaActionPerformed
        float base = Float.parseFloat(testoBase.getText());
        float altezza = Float.parseFloat(testoAltezza.getText());
        float area = base*altezza;
        risultato.setText(area+"");
    }//GEN-LAST:event_pulsanteCalcolaActionPerformed

    private void testoAltezzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testoAltezzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testoAltezzaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAltezza;
    private javax.swing.JLabel labelBase;
    private javax.swing.JButton pulsanteCalcola;
    private javax.swing.JLabel risultato;
    private javax.swing.JTextField testoAltezza;
    private javax.swing.JTextField testoBase;
    // End of variables declaration//GEN-END:variables
}
