/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanel;

/**
 *
 * @author gabriele.urban
 */
public class MainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainJPanel
     */
    public MainJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBase = new javax.swing.JLabel();
        labelAltezza = new javax.swing.JLabel();
        testoBase = new javax.swing.JTextField();
        testoAltezza = new javax.swing.JTextField();
        pulsanteCalcola = new javax.swing.JButton();
        risultato = new javax.swing.JLabel();
        Titolo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelBase.setText("base");
        add(labelBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        labelAltezza.setText("altezza");
        add(labelAltezza, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        testoBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testoBaseActionPerformed(evt);
            }
        });
        add(testoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 98, -1));

        testoAltezza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testoAltezzaActionPerformed(evt);
            }
        });
        add(testoAltezza, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 98, -1));

        pulsanteCalcola.setText("calcola");
        pulsanteCalcola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteCalcolaActionPerformed(evt);
            }
        });
        add(pulsanteCalcola, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        risultato.setBackground(new java.awt.Color(0, 0, 0));
        risultato.setForeground(new java.awt.Color(0, 146, 0));
        risultato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        risultato.setText("dato calcolato");
        risultato.setToolTipText("");
        risultato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 0, 15), 1, true));
        add(risultato, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 120, 30));

        Titolo.setText("Calcolatore area triangolo");
        add(Titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void testoBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testoBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testoBaseActionPerformed

    private void pulsanteCalcolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteCalcolaActionPerformed
        try{
            float base = Float.parseFloat(testoBase.getText());
            float altezza = Float.parseFloat(testoAltezza.getText());
            float area = base*altezza;
            risultato.setText(area+"");
        }catch(NumberFormatException e){
            risultato.setText("Valori non validi");
        }
    }//GEN-LAST:event_pulsanteCalcolaActionPerformed

    private void testoAltezzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testoAltezzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testoAltezzaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titolo;
    private javax.swing.JLabel labelAltezza;
    private javax.swing.JLabel labelBase;
    private javax.swing.JButton pulsanteCalcola;
    private javax.swing.JLabel risultato;
    private javax.swing.JTextField testoAltezza;
    private javax.swing.JTextField testoBase;
    // End of variables declaration//GEN-END:variables
}
