/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crm;

/**
 *
 * @author gabriele.urban
 */
public class Panel extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        listamembri = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        salva = new javax.swing.JButton();
        carica = new javax.swing.JButton();
        Out = new javax.swing.JLabel();
        cancMem = new javax.swing.JButton();
        iscrivimembro = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listamembri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(lista);

        listamembri.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 230, 240));

        salva.setText("Salva");
        listamembri.add(salva, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        carica.setText("Carica");
        listamembri.add(carica, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        Out.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Out.setText(" ");
        listamembri.add(Out, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        cancMem.setText("Cancella membro");
        listamembri.add(cancMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jTabbedPane1.addTab("Lista membri", listamembri);

        iscrivimembro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("jTextField1");
        iscrivimembro.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jTextField2.setText("jTextField2");
        iscrivimembro.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel2.setText("jLabel2");
        iscrivimembro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel3.setText("jLabel3");
        iscrivimembro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jButton2.setText("jButton2");
        iscrivimembro.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jButton3.setText("jButton3");
        iscrivimembro.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jTabbedPane1.addTab("Iscrivi membro", iscrivimembro);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Out;
    private javax.swing.JButton cancMem;
    private javax.swing.JButton carica;
    private javax.swing.JPanel iscrivimembro;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JList<String> lista;
    private javax.swing.JPanel listamembri;
    private javax.swing.JButton salva;
    // End of variables declaration//GEN-END:variables
}
